@url = http://localhost:5000

GET {{url}}/users/list

###
POST  {{url}}/users/create
Content-Type: application/json

{
    "name": "luis manuel",
    "surname": "gonzalez",
    "email": "uo269502@uniovi.es",
    "password": "1234"
}