[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
This is a group project oriented to the ASW subject and with this it is 
intended to learn to work in teams in a professional way and to manage 
and develop a project continuously.
The application will be an online store of all types of vehicles. 
Customer data must be secure and only be accessed by its owners, respecting the SOLID principles.
Within project management, there are two stakeholders:
* On the one hand, the developers, who intend to create a project to match, of a 
professional nature or, at least, that appears so. In addition, we intend that it 
meets, at least, the requirements imposed by the teachers.
* On the other hand, the professors, the people who have imposed on us the development of 
the project together with its restrictions.
****

=== Requirements Overview

[role="arc42help"]
****

This application aims to be a digital store for all kinds of second-hand vehicles. 
The store must respect the privacy of customers by complying with the SOLID principles, 
that is, store customer data through personal web servers (Pods), but only if they allow it.
The main expected functionality is:
* Show the catalog of available vehicles, in such a way that any user can access any that is 
for sale, even if they do not register.
* Purchase of vehicles by customers, which can be purchased by anyone as long as it is for 
sale and they have logged in.
* Modification of the catalog: apart from the clients, there will be an administrator user 
who will be able to add or remove vehicles from the application's list of vehicles for sale.
* Registration: for a user to be able to buy any vehicle, they must sign up as a client of the application.
* Login: if a user has previously registered, they must be able to log back in with all of 
their previously saved data.
Other functional requirements that the application must meet is to calculate the costs of a purchase 
from a customer based on the selected products and the shipping distance of these. Customers must 
also be able to view the orders placed at all times.
****

=== Quality Goals

[role="arc42help"]
****

[options="header",cols="1,2,2"]
|===
|Nº|Quality attribute|Motivation
| _1_ | _Usability_ | _Users should be able to use the page with little difficulty without having to search for instructions for use. A web application is useless if no one knows how to handle it._
| _2_ | _Security_ | _The application must be able to resist attack from anyone trying to take down the application or extract information from it without authorization. If a user doesn't feel safe in the app, they might leave the app._
| _3_ | _Confidentiality_ | _Customer data can only be accessed by them, and the store manager must be the only one capable of changing the available stock._
|===
****

=== Stakeholders

[role="arc42help"]
****

There are various stakeholders related to the 
application to be developed. These are the relevant ones:
* Developers: they are the people in charge of developing the 
project and researching tools to be used in the project, 
which, in this case, are the members of the 6-c laboratory 
team.
* Professors: they are the people who “finance” the development 
of the project. These would be the teachers of the ASW subject, 
in charge of evaluating the development of the project.
****
