[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
*APPNAME* is a web application focused on allowing users to buy used vehicles, ranging from simple bicycles all the way to automobiles.
Clients will be able to browse and buy different vehicles they like on our web, as long as they have signed up, and are signed in. They will need to provide our services with a billing address and payment method in order to let us process their purchase.
****

=== Business Context

[role="arc42help"]
****
We have clients who want to buy used vehicles. The clients need to sign up in order to use the application. The vehicles that clients will be buying are already registered in the application's database, they are not uploaded by sellers. Orders are used to link a buyer with the vehicle, or vehicles that they are buying, and will be shipped to their home.

The data in exchange is simple. The client will be able to see information about the vehicle, such as its brand, model, fuel type, as well as pictures of it, in order to see its state.
The store will need the clients' full name, billing address, age, username and a password to store their information.
At least a payment mean will be needed for the client to be able to make purchases.
The seller (the application, in this case), on the other hand, will receive the client's billing address, so as to be able to ship the vehicle, as well as their full name in order to recognize them.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****

**<Diagram or Table>**

**<optionally: Explanation of external domain interfaces>**

=== Technical Context

[role="arc42help"]
****
The application will be deployed online, and will be accessible through any modern web browser. To develop its frontend we will be using React. We will use MongoDB as our database, and we will link the backend and frontend with Express. The application will be writen in TypeScript, a JavaScript extension, so to speak, that lets programmers use a very similar syntax to that of JS, but will allow us to avoid common mistakes through the use of static type checking. 

We will be using the Solid architecture, with the objective of protecting our users' information, only giving access to the data they want to provide us, which will be necessary for us to process their purchases.

The main objective of this system is to provide users who want to buy used vehicles a safe space to use for this purpose, where only the information they want to share is used, and especially not taken from them. Every purchase they make will be stored in our database, but is not our property. This means, if at any given time a client decides to hide this information from us, they are in their right.

****
|===
|*System* |*Utility*
| Solid | We use Solid to protect our users' private information.
| MongoDB | It allows us to store the data regarding clients, orders, and products.
| TypeScript | The language chosen to code the system and give it all its functionality.
| Express |JavaScript library that allows us to link the database with the frontend.
| React | JavaScript library used to create the frontend. It is based on components.
|===

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
