[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Design changes
The following decisions have been made regarding the design of the application architecture:
* The decision has been made to use the MERN architectural stack in the project, consisting of MongoDB, Express, React, Node. The reason is that since the use of React, Express and Node is a restriction, we thought it was good to apply the architectural stack by adding MongoDB as a tool to the project.
* Docker: this tool is intended to ease the development of the project by avoiding certain repetitive and costly tasks, that is, it was chosen to ease the development of the project.
* To be able to deploy the application so that it can be used by anyone, a deployment service is required. The one that has been chosen is Heroku, since it supports a large number of programming languages, including TypeScript with React. Furthermore, it is easily usable just by linking the Github repository to said tool.
* AsciiDoc: it has been chosen to use this tool to ease the elaboration of the documentation throughout the development.
****
